<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>subrat-code-base</groupId>
		<artifactId>openai</artifactId>
		<version>1.0</version>
	</parent>

	<artifactId>openai-service</artifactId>
	<name>openai-service</name>

	<dependencies>

		<dependency>
			<groupId>subrat-code-base</groupId>
			<artifactId>openai-repository</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>subrat-code-base</groupId>
			<artifactId>security-config</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>subrat-code-base</groupId>
			<artifactId>openai-client</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-model-openai</artifactId>
		</dependency>

	</dependencies>

</project>
