server:
  port: 8079

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            ###---------- USER PUBLIC --------------

            - id: user-mgmt-public-api
              uri: lb://user-mgmt
              predicates:
                - Path=/user-mgmt/api/v1/validate/user,/user-mgmt/api/v1/register-normal-user,/user-mgmt/api/v1/reset-password-with-otp,/user-mgmt/api/v1/send-forgot-password-otp,/user-mgmt/api/v1/verify-otp
              filters:
                - PreserveHostHeader

            ###---------- USER AUTH --------------

            - id: user-mgmt-authenticated
              uri: lb://user-mgmt
              predicates:
                - Path=/user-mgmt/api/v1/**
              filters:
                - GlobalAuthHeaderFilter
                - PreserveHostHeader

            ###---------- PRODUCT AUTH --------------

            - id: product-mgmt-authenticated
              uri: lb://product-mgmt
              predicates:
                - Path=/product-mgmt/api/v1/**
              filters:
                - GlobalAuthHeaderFilter
                - PreserveHostHeader

            ###---------- SECURITY PUBLIC --------------

            - id: security-public-api
              uri: lb://security
              predicates:
                - Path=/security/api/v1/login
              filters:
                - PreserveHostHeader

            ###---------- SECURITY AUTH --------------

            - id: security-authenticated
              uri: lb://security
              predicates:
                - Path=/security/api/v1/**
              filters:
                - GlobalAuthHeaderFilter
                - PreserveHostHeader

            ###---------- EMAIL PUBLIC --------------

            - id: email-public-api
              uri: lb://email
              predicates:
                - Path=/email/api/v1/send-email
              filters:
                - PreserveHostHeader

            ###---------- EMAIL AUTH --------------

            - id: email-authenticated
              uri: lb://email
              predicates:
                - Path=/email/api/v1/**
              filters:
                - GlobalAuthHeaderFilter
                - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "https://kamlamedical.com"
                  - "https://www.kamlamedical.com"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

  jwt:
    secret: bXlTdXBlclNlY3VyZUhTNTEyS2V5VGhhdElzQXRMZWFzdDY0Qnl0ZXNMb25nRm9yU2VjdXJlSldUVG9rZW5TaWduaW5nMTIzNDU2
    access-ttl-seconds: 36000
    refresh-ttl-seconds: 86400
    issuer: ${DOMAIN_NAME}